version: "3"
services:
  web_server:
    build: .
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html/
    links:
      - db
    networks:
      - default

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: SIH
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
volumes:
    persistent:

